import os
import json
import time
import threading
import subprocess
from datetime import datetime, timedelta

from core.resource_gate import acquire_resource, release_resource
from .ytdlp_service import download_source
from .ffmpeg_service import process_clip_pro
from .ai_engine import get_viral_moments, generate_lyrics_srt

DB_PATH = os.path.join(os.path.dirname(__file__), 'clips_db.json')
CHANNELS_DB = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'channels_db.json')
_db_lock = threading.Lock()

def read_db():
    with _db_lock:
        if not os.path.exists(DB_PATH): return []
        try:
            with open(DB_PATH, 'r') as f: return json.load(f)
        except: return []

def write_db(data):
    with _db_lock:
        with open(DB_PATH, 'w') as f: json.dump(data, f, indent=4)

def update_job(job_id, status=None, progress=None, stage=None, output_file=None):
    jobs = read_db()
    for job in jobs:
        if job['id'] == job_id:
            if status is not None: job['status'] = status
            if progress is not None: job['progress'] = progress
            if stage is not None: job['stage'] = stage
            if output_file is not None: job['output_file'] = output_file
            break
    write_db(jobs)

def upload_to_youtube(video_path, job_data):
    try:
        from googleapiclient.discovery import build
        from google.oauth2.credentials import Credentials
        from googleapiclient.http import MediaFileUpload
        from zoneinfo import ZoneInfo
        
        target_id = job_data.get('options', {}).get('targetChannelId')
        
        with open(CHANNELS_DB, 'r') as f:
            channels = json.load(f)
            
        channel = next((c for c in channels if c.get('yt_id') == target_id), None)
        if not channel: raise Exception("Channel Target tidak ditemukan di database!")
        
        creds_str = channel.get('creds_list', [channel.get('creds_json')])[0]
        creds = Credentials.from_authorized_user_info(json.loads(creds_str))
        youtube = build('youtube', 'v3', credentials=creds)
        
        title = f"Viral Moment #{job_data['batch_index']} #shorts"
        body = {
            'snippet': {'title': title, 'description': 'Auto-generated by KeiBot Clipper Pro', 'categoryId': '24'},
            'status': {'privacyStatus': 'private'}
        }
        
        if job_data.get('publish_date'):
            sch_obj = datetime.strptime(job_data['publish_date'], "%Y-%m-%dT%H:%M")
            sch_obj += timedelta(days=(job_data['batch_index'] - 1))
            wib = ZoneInfo("Asia/Jakarta")
            import datetime as dt
            sch_utc = sch_obj.replace(tzinfo=wib).astimezone(dt.timezone.utc)
            body['status']['publishAt'] = sch_utc.strftime("%Y-%m-%dT%H:%M:%S.000Z")

        media = MediaFileUpload(video_path, resumable=True)
        req = youtube.videos().insert(part=','.join(body.keys()), body=body, media_body=media)
        
        response = None
        while response is None:
            status, response = req.next_chunk()
            if status:
                update_job(job_data['id'], progress=int(status.progress()*100), stage=f"Mengunggah ke YT... {int(status.progress()*100)}%")
                
        return response.get('id')
    except Exception as e:
        raise Exception(f"Gagal Upload YT: {str(e)}")

def clipper_worker_loop():
    print("🚀 [Clipper Pro Worker] Background thread dimulai...")
    while True:
        try:
            jobs = read_db()
            job_to_run = next((j for j in jobs if j.get('status') == 'queued'), None)

            if job_to_run:
                job_id = job_to_run['id']
                opts = job_to_run.get('options', {})
                batch_idx = job_to_run.get('batch_index', 1)
                total_batch = job_to_run.get('total_batch', 1)
                
                update_job(job_id, status='processing', stage='Menunggu slot CPU/RAM kosong...')
                acquire_resource(worker_name="Clipper Worker")
                
                temp_files = []
                try:
                    # 1. DOWNLOAD
                    update_job(job_id, status='downloading', progress=20, stage='Mengunduh video sumber...')
                    source_path = download_source(url=job_to_run['url'], video_id=job_id.split('_')[0], resolution="1080p")
                    
                    # 2. DETEKSI VIRAL MOMENT (AI)
                    update_job(job_id, status='clipping', progress=40, stage='Menganalisis momen viral (AI)...')
                    moments = get_viral_moments(source_path, count=total_batch, duration_sec=40)
                    my_moment = moments[batch_idx - 1] if batch_idx <= len(moments) else moments[0]
                    
                    start_time = my_moment['start']
                    duration = my_moment['duration']
                    
                    # --- PERSIAPAN AUDIO BGM DILAKUKAN LEBIH AWAL ---
                    bgm_file = opts.get('bgmFile', 'none')
                    audio_mode = opts.get('audioMode', 'bgm')
                    asset_id = opts.get('assetChannelId', '')
                    bgm_path = None
                    
                    if bgm_file != 'none' and asset_id:
                        bgm_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'uploads', asset_id, bgm_file)
                    
                    # 3. POTONG AUDIO & GENERATE LIRIK (Auto-Switch Sumber Suara)
                    srt_path = None
                    if opts.get('lyricStyle') != 'none':
                        update_job(job_id, status='clipping', progress=60, stage='Generate Lirik via AI...')
                        audio_clip = f"{source_path}_{job_id}_audio.mp3"
                        temp_files.append(audio_clip)
                        
                        # LOGIKA PINTAR: Pilih suara apa yang akan didengarkan oleh AI
                        if audio_mode == "replace" and bgm_path and os.path.exists(bgm_path):
                            # Jika Mute Mode: Potong lagu BGM sesuai durasi video dan kirim ke AI
                            subprocess.run(['/usr/bin/ffmpeg', '-y', '-stream_loop', '-1', '-i', bgm_path, '-t', str(duration), '-q:a', '0', '-map', 'a', audio_clip], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                        else:
                            # Jika BGM Mode: Potong suara asli dari video dan kirim ke AI
                            subprocess.run(['/usr/bin/ffmpeg', '-y', '-ss', str(start_time), '-t', str(duration), '-i', source_path, '-q:a', '0', '-map', 'a', audio_clip], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                        
                        # Rotasi global lintas semua provider.
                        # ai_provider lama tidak lagi membatasi penggunaan token.
                        srt_path = generate_lyrics_srt(
                            audio_clip,
                            job_to_run.get('api_keys', []),
                            provider='auto'
                        )
                        if srt_path: temp_files.append(srt_path)

                    # 4. RENDER FINAL (Crop + Visualizer + Lirik + Audio Mix)
                    update_job(job_id, status='encoding', progress=80, stage='Rendering Efek & Filter FFmpeg...')
                    output_name = f"clip_{job_id}.mp4"
                    output_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'static', output_name)
                    
                    process_clip_pro(
                        source_path=source_path,
                        output_path=output_path,
                        start_time=start_time,
                        duration=duration,
                        crop_mode=opts.get('cropMode', 'center'),
                        lyric_style=opts.get('lyricStyle', 'none'),
                        srt_path=srt_path,
                        use_visualizer=opts.get('useVisualizer', False),
                        bgm_path=bgm_path,
                        audio_mode=audio_mode,
                        custom_font=opts.get('customFont', '')
                    )
                    
                    # 5. DESTINASI OUTPUT
                    dest = opts.get('outputDest', 'local')
                    target_id = opts.get('targetChannelId', '')
                    
                    if dest == 'youtube' and target_id:
                        update_job(job_id, status='encoding', progress=95, stage='Proses Upload ke YouTube...')
                        yt_id = upload_to_youtube(output_path, job_to_run)
                        final_msg = f"Selesai & Dijadwalkan! (YT ID: {yt_id})"
                    elif dest == 'drive':
                        update_job(job_id, status='encoding', progress=95, stage='Mengirim ke Google Drive...')
                        final_msg = "Selesai (Tersimpan di Drive)"
                    elif dest == 'dropbox':
                        update_job(job_id, status='encoding', progress=95, stage='Mengirim ke Dropbox...')
                        final_msg = "Selesai (Tersimpan di Dropbox)"
                    else:
                        final_msg = "Selesai (Tersimpan di Galeri/Lokal)."

                    update_job(job_id, status='done', progress=100, stage=final_msg, output_file=output_name)
                    print(f"✅ [Clipper Worker] Job {job_id} selesai.")
                    
                except Exception as e:
                    print(f"❌ [Clipper Worker] Error job {job_id}: {e}")
                    update_job(job_id, status='error', stage=f'Error: {str(e)}')
                
                finally:
                    for tf in temp_files:
                        if os.path.exists(tf): 
                            try: os.remove(tf)
                            except: pass
                    
                    if batch_idx == total_batch and 'source_path' in locals():
                        if os.path.exists(source_path):
                            try: os.remove(source_path)
                            except Exception as e: pass

                    release_resource(worker_name="Clipper Worker")
                    
        except Exception as main_e:
            print(f"⚠️ [Clipper Worker] Fatal error: {main_e}")
            
        time.sleep(2)

threading.Thread(target=clipper_worker_loop, daemon=True).start()